name: apidocs

on:
  push:
    branches:
      - 'master'
      - 'feature/docker-ci'

jobs:
  updateAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Install Ego Gen API
        id: egogen
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          go version 
          go install github.com/gotomicro/ego-gen-api/cmd/egogen@v0.0.6
          egogen --config egogen.yaml
      - name: Install ossutil
        run: wget http://gosspublic.alicdn.com/ossutil/1.7.3/ossutil64 && chmod 755 ossutil64
      - name: Config ossutil
        run: ./ossutil64 config -e oss-cn-beijing.aliyuncs.com -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - name: Upload docs
        run: ./ossutil64 cp -r -f ./api/docs/swagger.json oss://gocn-cdn/clickvisual/api/swagger/doc.json
      - name: Create Commit
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          delete-branch: true
          commit-message: 'docs: update api docs'
          title: update api docs
