name: Update EGO Gen API

on:
  push:
    branches:
      - 'feature/docker-ci'

jobs:
  updateAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Install Ego Gen API
        id: swagger-ui
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          go version 
          go install github.com/gotomicro/ego-gen-api/cmd/egogen@v0.0.1-rc1
          egogen --config egogen.yaml
      - name: Create Commit
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          delete-branch: true
          commit-message: 'docs: update ego gen api'
          title: Update EGO Gen API
