name: Update Swagger UI

on:
  push:
    branches:
      - 'feature/docker-ci'

jobs:
  updateSwagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Swagger
        id: swagger-ui
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          go install github.com/gotomicro/ego-gen-api/cmd/egen@latest
          go env
          egen --config egen.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          delete-branch: true
          commit-message: 'docs: swagger update'
          title: Update Swagger
          body: |
            Updates [swagger-ui]
